name: clear-deploy

# 在master分支发生push事件时触发。
on: workflow_dispatch

env: # 设置环境变量
  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用时区时间）

jobs:
  build: # 自定义名称
    runs-on: ubuntu-latest # 运行在虚拟机环境ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"
      - name: Build
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |
          pnpm install
          pnpm run build

      - name: Deploy upyun
        run: |
          wget -O upx.tar.gz https://github.com/upyun/upx/releases/download/v0.4.4/upx_0.4.4_Linux_x86_64.tar.gz
          tar -zxf upx.tar.gz
          chmod +x upx
          ./upx login ${{ secrets.UP_BUCKET }} ${{ secrets.UP_OPERATOR }} ${{ secrets.UP_OPERATOR_PASSWORD }}
          ./upx rm / -a
          ./upx upload dist/* --remote / -all -w 10
          ./upx logout

      # - name: Deploy github
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     publish_dir: ./dist
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     user_name: "github-actions[bot]"
      #     user_email: "github-actions[bot]@users.noreply.github.com"
